/**
 * Central icon registry for all landing pages.
 *
 * - Social/brand icons → FontAwesome brands (`<SocialIcon name="instagram" />`)
 * - UI icons → Lucide React, exposed as `Icon.*` from an explicit registry
 *   (add the icon to the import + registry below before using it)
 * - Extra icon sets (Heroicons, Feather, Bootstrap, etc.) → `react-icons` (import directly where needed)
 *
 * Import everywhere from `@/components/icons`.
 */

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faInstagram,
  faXTwitter,
  faFacebookF,
  faLinkedinIn,
  faTiktok,
  faYoutube,
  faWhatsapp,
  faSnapchat,
  faPinterestP,
  faTelegram,
  faGithub,
} from "@fortawesome/free-brands-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

const socialMap = {
  instagram: faInstagram,
  x: faXTwitter,
  twitter: faXTwitter,
  facebook: faFacebookF,
  linkedin: faLinkedinIn,
  tiktok: faTiktok,
  youtube: faYoutube,
  whatsapp: faWhatsapp,
  snapchat: faSnapchat,
  pinterest: faPinterestP,
  telegram: faTelegram,
  github: faGithub,
} as const satisfies Record<string, IconDefinition>;

export type SocialName = keyof typeof socialMap;

type SocialIconProps = {
  name: SocialName;
  className?: string;
  size?: "xs" | "sm" | "lg" | "xl" | "2x" | "3x";
};

export function SocialIcon({ name, className, size }: SocialIconProps) {
  return <FontAwesomeIcon icon={socialMap[name]} className={className} size={size} />;
}

// UI icons — an explicit registry, NOT a namespace re-export.
// `import * as LucideIcons` pulled all ~1500 lucide icons into every page
// (≈580KB of JS); naming them lets the bundler ship only what is used.
// Call sites keep the same `<Icon.ArrowLeft />` shape, and because `Icon`
// is a plain object TypeScript now fails the build on a missing icon.
import {
  Activity,
  AlertCircle,
  AlignJustify,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioWaveform,
  Award,
  BadgeCheck,
  Bandage,
  BedDouble,
  Cable,
  CalendarCheck,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeftRight,
  CircleAlert,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock3,
  Columns2,
  CreditCard,
  Crown,
  Dna,
  Droplet,
  Droplets,
  Eye,
  Flame,
  FlaskConical,
  Flower2,
  Footprints,
  Frown,
  Gem,
  Gift,
  GraduationCap,
  Grip,
  Hand,
  HeartHandshake,
  Layers,
  Leaf,
  Link2,
  Lock,
  MapPin,
  Menu,
  MessageCircle,
  MessageCircleQuestion,
  Microscope,
  Moon,
  MoveDown,
  MoveUpLeft,
  Navigation,
  Palette,
  PenTool,
  Phone,
  Pipette,
  Plus,
  Quote,
  Radio,
  RefreshCw,
  Route,
  Scale,
  ScanFace,
  ScanSearch,
  Scissors,
  ShieldCheck,
  ShowerHead,
  Slice,
  Smartphone,
  Smile,
  Sparkles,
  Spline,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Target,
  TestTubes,
  TrendingUp,
  TriangleAlert,
  Users,
  Waves,
  Wheat,
  Wind,
  X,
  Zap,
} from "lucide-react";

export const Icon = {
  Activity,
  AlertCircle,
  AlignJustify,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioWaveform,
  Award,
  BadgeCheck,
  Bandage,
  BedDouble,
  Cable,
  CalendarCheck,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeftRight,
  CircleAlert,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock3,
  Columns2,
  CreditCard,
  Crown,
  Dna,
  Droplet,
  Droplets,
  Eye,
  Flame,
  FlaskConical,
  Flower2,
  Footprints,
  Frown,
  Gem,
  Gift,
  GraduationCap,
  Grip,
  Hand,
  HeartHandshake,
  Layers,
  Leaf,
  Link2,
  Lock,
  MapPin,
  Menu,
  MessageCircle,
  MessageCircleQuestion,
  Microscope,
  Moon,
  MoveDown,
  MoveUpLeft,
  Navigation,
  Palette,
  PenTool,
  Phone,
  Pipette,
  Plus,
  Quote,
  Radio,
  RefreshCw,
  Route,
  Scale,
  ScanFace,
  ScanSearch,
  Scissors,
  ShieldCheck,
  ShowerHead,
  Slice,
  Smartphone,
  Smile,
  Sparkles,
  Spline,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Target,
  TestTubes,
  TrendingUp,
  TriangleAlert,
  Users,
  Waves,
  Wheat,
  Wind,
  X,
  Zap,
} as const;


// FontAwesome solid set is also available if a landing needs it.
export { FontAwesomeIcon };
